import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [
        'getting-started/installation',
        'getting-started/quick-start',
        'getting-started/configuration',
        'getting-started/client-libraries',
      ],
    },
    {
      type: 'category',
      label: 'Core Concepts',
      items: [
        'core-concepts/architecture',
        'core-concepts/data-types',
        'core-concepts/persistence-model',
        'core-concepts/consistency-model',
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      items: [
        'guides/embedded-mode',
        'guides/server-mode',
        'guides/persistence',
        'guides/transactions',
        'guides/vector-search',
        'guides/semantic-caching',
        'guides/pub-sub',
        'guides/lua-scripting',
        'guides/ttl-expiration',
        'guides/connection-pooling',
      ],
    },
    {
      type: 'category',
      label: 'Data Models',
      items: [
        'data-models/document-store',
        'data-models/graph-database',
        'data-models/time-series',
        'data-models/full-text-search',
        'data-models/crdt',
      ],
    },
    {
      type: 'category',
      label: 'AI & Machine Learning',
      items: [
        'ai-ml/overview',
        'ai-ml/embeddings',
        'ai-ml/vector-indexes',
        'ai-ml/semantic-search',
        'ai-ml/rag-pipeline',
        'ai-ml/llm-caching',
      ],
    },
    {
      type: 'category',
      label: 'Event-Driven',
      items: [
        'event-driven/cdc',
        'event-driven/triggers',
        'event-driven/streams',
        'event-driven/webhooks',
      ],
    },
    {
      type: 'category',
      label: 'Query',
      items: [
        'query/ferriteql',
        'query/materialized-views',
        'query/aggregations',
        'query/prepared-statements',
      ],
    },
    {
      type: 'category',
      label: 'Extensibility',
      items: [
        'extensibility/wasm-functions',
        'extensibility/plugin-system',
        'extensibility/custom-commands',
        'extensibility/custom-data-types',
      ],
    },
    {
      type: 'category',
      label: 'Operations',
      items: [
        'operations/monitoring',
        'operations/observability',
        'operations/backup-restore',
        'operations/performance-tuning',
        'operations/troubleshooting',
        'operations/audit-logging',
      ],
    },
    {
      type: 'category',
      label: 'Performance',
      items: [
        'performance/benchmarks',
      ],
    },
    {
      type: 'category',
      label: 'Deployment',
      items: [
        'deployment/docker',
        'deployment/kubernetes',
        'deployment/cloud-providers',
        'deployment/high-availability',
        'deployment/capacity-planning',
      ],
    },
    {
      type: 'category',
      label: 'Multi-Tenancy',
      items: [
        'multi-tenancy/overview',
        'multi-tenancy/tenant-isolation',
        'multi-tenancy/quotas-limits',
        'multi-tenancy/tenant-migration',
      ],
    },
    {
      type: 'category',
      label: 'Migration',
      items: [
        'migration/from-redis',
        'migration/from-memcached',
        'migration/compatibility',
        'migration/migration-tools',
      ],
    },
    {
      type: 'category',
      label: 'Advanced',
      items: [
        'advanced/clustering',
        'advanced/replication',
        'advanced/security',
        'advanced/encryption',
        'advanced/rdma',
        'advanced/tiered-storage',
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      items: [
        {
          type: 'category',
          label: 'Commands',
          items: [
            'reference/commands/strings',
            'reference/commands/lists',
            'reference/commands/hashes',
            'reference/commands/sets',
            'reference/commands/sorted-sets',
            'reference/commands/streams',
            'reference/commands/hyperloglog',
            'reference/commands/geo',
            'reference/commands/bitmap',
            'reference/commands/pubsub',
            'reference/commands/transactions',
            'reference/commands/scripting',
            'reference/commands/server',
            'reference/commands/cluster',
            'reference/commands/vector',
            'reference/commands/semantic',
            'reference/commands/temporal',
            'reference/commands/document',
            'reference/commands/graph',
            'reference/commands/timeseries',
            'reference/commands/search',
            'reference/commands/cdc',
            'reference/commands/trigger',
            'reference/commands/wasm',
            'reference/commands/crdt',
            'reference/commands/query',
            'reference/commands/tenant',
          ],
        },
        'reference/configuration',
        'reference/api',
        'reference/cli',
        'reference/tui',
        'reference/errors',
        'reference/glossary',
      ],
    },
    {
      type: 'category',
      label: 'Client SDKs',
      items: [
        'sdks/overview',
        {
          type: 'category',
          label: 'Quick Start',
          items: [
            'sdks/python',
            'sdks/nodejs',
            'sdks/go',
            'sdks/rust',
          ],
        },
        {
          type: 'category',
          label: 'Language Reference',
          items: [
            'sdk/rust',
            'sdk/python',
            'sdk/typescript',
            'sdk/go',
            'sdk/java',
            'sdk/csharp',
            'sdk/php',
            'sdk/ruby',
            'sdk/elixir',
            'sdk/swift',
          ],
        },
        {
          type: 'category',
          label: 'AI SDKs',
          items: [
            'sdks/ai-overview',
            'sdks/python-ai-sdk',
            'sdks/typescript-ai-sdk',
          ],
        },
        'sdk/generator',
      ],
    },
    {
      type: 'category',
      label: 'Observability',
      items: [
        'observability/overview',
        'observability/opentelemetry',
        'observability/distributed-tracing',
        'observability/grafana',
        'observability/datadog',
        'observability/newrelic',
      ],
    },
    {
      type: 'category',
      label: 'Integrations',
      items: [
        'integrations/langchain',
        'integrations/llamaindex',
        'integrations/huggingface',
      ],
    },
    {
      type: 'category',
      label: 'Tutorials',
      items: [
        'tutorials/build-chat-app',
        'tutorials/build-leaderboard',
        'tutorials/build-session-store',
        'tutorials/build-rate-limiter',
        'tutorials/build-recommendation-engine',
        'tutorials/build-semantic-search',
        'tutorials/build-rag-chatbot',
        'tutorials/build-event-sourcing',
        'tutorials/build-analytics-dashboard',
        'tutorials/build-multi-tenant-saas',
        'tutorials/semantic-caching-quickstart',
        'tutorials/ferriteql-quickstart',
        'tutorials/embedded-iot',
      ],
    },
    {
      type: 'category',
      label: 'Features',
      items: [
        'features/embedded-mode',
        'features/semantic-caching',
        'features/ferriteql',
      ],
    },
    {
      type: 'category',
      label: 'Use Cases',
      items: [
        'use-cases/caching',
        'use-cases/session-management',
        'use-cases/real-time-analytics',
        'use-cases/feature-flags',
        'use-cases/message-queues',
        'use-cases/geospatial',
        'use-cases/ml-feature-store',
        'use-cases/iot-telemetry',
      ],
    },
    {
      type: 'category',
      label: 'Comparisons',
      items: [
        'comparisons/vs-redis',
        'comparisons/vs-dragonfly',
        'comparisons/vs-keydb',
        'comparisons/vs-memcached',
        'comparisons/vs-dedicated-dbs',
      ],
    },
    {
      type: 'category',
      label: 'Internals',
      items: [
        'internals/hybridlog',
        'internals/epoch-reclamation',
        'internals/io-uring',
        'internals/resp-protocol',
        'internals/testing',
      ],
    },
    {
      type: 'category',
      label: 'Community',
      items: [
        'community/contributing',
        'community/roadmap',
        'community/faq',
        'community/changelog',
        'community/governance',
        'community/support',
      ],
    },
  ],
};

export default sidebars;
